# Generated by Django 2.2.19 on 2023-01-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230129_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_added',
            new_name='pub_date',
        ),
    ]
